### ISSUE TITLE
Screen viewport / aspect ratio?

### ISSUE THREAD

**Issue by eboatwright** [Nazariglez/notan#126]
I saw this pull request while looking for other Issues:
https://github.com/Nazariglez/notan/pull/28
But I wasn't able to find the files / imports for Scaler and ScalerMode.
Any help appreciated!

**Comment by Nazariglez** [comment]
Hello! 

This was from an early version of Notan. The scaler was deprecated because it fits more into a game engine than in a "foundation library", though you can browse the files `Transform2d` and `Scaler` here: https://github.com/Nazariglez/notan/tree/937c89c540465f2665e532def0e93be041d41234/src/extras 

Is quite simple, just stacking some matrixes to do the effect of a 2d camera and fit the content of your game in some resolution.

Nowadays if I am using the `Draw2d` API I use a simple function that returns a projection to fit the content on the screen (`AspectFit`). I added an example with it: [draw_projection](https://github.com/Nazariglez/notan/blob/develop/examples/draw_projection.rs)

Check this gif, not the best quality but it shows the idea:
![projection](https://user-images.githubusercontent.com/1929191/185744905-25fc6d86-4ce9-4317-9e6d-2cac022b9f0b.gif)

At the end of the day, it depends on what your project needs. You can reproduce the code for the scaler and have multiple scaler modes, or use a simple function to get the projection you want. In case you go with the projection function and want another "mode" let me know, we can modify it a little to get the `Fill` or `AspectFill` modes. 

I hope that this helps, let me know if you need anything!

**Comment by eboatwright** [comment]
This is perfect! What about using rendering?

**Comment by Nazariglez** [comment]
It will depend on a lot of things using the `Renderer` object because it's a low-level API. Are you going to draw 2d or 3d? Perspective or orthographic? Normalized coordinates? In general, the process should be quite similar, but the dev should add a transform matrix in the shader and pass the data as a uniform buffer.

Using an orthographic projection the same method that we use with the `Draw2d` API should work, and using a perspective matrix we can set the `aspect_ratio` creating the [matrix](https://docs.rs/notan/latest/notan/math/struct.Mat4.html#method.perspective_lh). 

Let's take this example: [renderer-cube](https://github.com/Nazariglez/notan/blob/develop/examples/renderer_cube.rs#L14). 
The vertex shader uses a `mat4` inside the uniform buffer `Locals` and then multiplies the vertex and this matrix to get the final position. The matrix is defined [here](https://github.com/Nazariglez/notan/blob/develop/examples/renderer_cube.rs#L122-L128) using `4.0 / 3.0` as aspect ratio, which is the same as `800.0 / 600.0`. And then [here](https://github.com/Nazariglez/notan/blob/develop/examples/renderer_cube.rs#L143-L147) is created the uniform buffer with the projection as initial data. 

In the `draw` function [we upload to the GPU](https://github.com/Nazariglez/notan/blob/develop/examples/renderer_cube.rs#L163) the uniform buffer with the matrix updated with the cube's rotation. 

Now if we make the window resizable with:
```    
notan::init_with(setup)
    .add_config(WindowConfig::default().resizable(true))
    .draw(draw)
    .build()
```

We see how the cube is deformed to adapt to the window's size:
![cube1](https://user-images.githubusercontent.com/1929191/185759232-9e614084-31b7-4c30-96e3-b116cfc15327.gif)

However, if we change the `mvp` each frame using the window's size:
```
    let (width, height) = gfx.size();
    let ratio = (width as f32) / (height as f32);
    let projection = Mat4::perspective_rh_gl(45.0, ratio, 0.1, 100.0);
    let view = Mat4::look_at_rh(
        Vec3::new(4.0, 3.0, 3.0),
        Vec3::new(0.0, 0.0, 0.0),
        Vec3::new(0.0, 1.0, 0.0),
    );
    let mvp = Mat4::IDENTITY * projection * view;
    state.mvp = mvp;
```

We will see how the cube is not deformed anymore:
![cube2](https://user-images.githubusercontent.com/1929191/185759503-c635777d-fe68-41e4-ba64-244003f4e06e.gif)

Though I am not an expert at all on graphics programming, it's safe to say that if something works on OpenGL should work the same on Notan because the graphics API is just a thin wrapper on top of it to make it more "easy" to work with. 

I hope that this helps!

**Comment by eboatwright** [comment]
Ok, thank you! By the way, the last time I used this library was at 0.1.0, and I have to say, it's really becoming amazing! :+1:

**Comment by Nazariglez** [comment]
I am very glad to hear that! I hope to keep improving it and get more adoption over time. 

Thanks for checking it again.

**Comment by eboatwright** [comment]
No problem! :smile:
