### ISSUE TITLE
Use non [u8] textures

### ISSUE THREAD

**Issue by jawadsh123** [Nazariglez/notan#135]
Hey 👋 

First of all, amazing project. We're using notan for a video editing app we're building (web is our primary target) and so far it feels rather nice!

We've hit a small snag on assets. It seems current strategy is to load images into wasm memory?
Folks can upload very large / very many images on our app, and since wasm has a [hard limit on memory](https://v8.dev/blog/4gb-wasm-memory), we might run out 😅 

An alternative is to use HTMLImageElement / ImageBitmap and blit it directly, with [texImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D)

Is there a way to achieve this with notan rn? Did look around but could be I missed something 😄 

Possible solutions
- expose underlying backend context ([maybe something similar to egui's callbacks?](https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/apps/custom3d_glow.rs#L65))
- support non [u8] texture sources within notan directly (had a rough go at it [here](https://github.com/jawadsh123/notan/commit/82f4d2febcfabde75552ba086f22a787854bb042), though dunno if it's the right approach)

**Comment by jawadsh123** [comment]
Ohh bdw we're exploring [WebCodecs](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API) for video decode/playback, and it seems the fastest way to blit [VideoFrames](https://developer.mozilla.org/en-US/docs/Web/API/VideoFrame) is also through texImage2D 🙃

**Comment by Nazariglez** [comment]
Hey, thanks for the kind words! 

This is quite an interesting case of use! 

One thing to notice is that the images are loaded into memory, then uploaded to the GPU, and then the memory is dropped. So they aren't kept in the memory forever, but I guess that if you're uploading giant images you can reach the limits. 

I am sure we can find a way to do what you need. Let me dig a little bit into this, and I'll come back to you in the next few days.

**Comment by Nazariglez** [comment]
I have been looking into this a little, sorry for the delay I have had a busy week. I think that your branch is a good change but I am not a fan of pollute `notan_graphics` with information on just one platform to cover an edge case. 

So I have been playing with the idea of exposing the backend as you mention, at least in a way that allows us to do this for now. Ideally, notan should be able to manage these edge cases with a better API, I'll think about it. 

Meanwhile, my idea is to expose the GL backend, and add a `plugin` in a different crate, that you can import and will allow you to do this without too much hassle.

Let me see if I am able to allocate some free time this week to make the changes needed.

**Comment by Nazariglez** [comment]
I am working on this at #138, I have already `HtmlImageElement` working on one example. However, it is quite experimental and wip. 

The API will remain (mostly) the same for the user, you will load/update the element as any other texture. 

I am still thinking/playing with the API and some issues between crates to make it work because the extensions expect the `TextureBuilder` to have methods like `from_bytes` that, with the new design they are not there because they are injected by the backend. So my main issue is to think how to keep everything working, allowing this new flexibility to create textures from elements without "trust" that some struct/traits will be on the backend, because backends are swappable and should be enough to create a backend only impl traits (maybe this is just fine and only needs to have better docs).

Anyway, still, some work to do, cleaning and improving, once ready I'll assign you as a reviewer. 

/cc @jawadsh123

**Comment by jawadsh123** [comment]
wow @Nazariglez, really like where this is headed! 
Extensible TextureSources are imo perfect, will allow impl'ing whatever esoteric sources people want without adding them all to notan

I don't see an obvious easy way out of the `from_bytes` situation though, maybe will have to be a breaking change 😅
