### ISSUE TITLE
RenderTarget should not draw inverted (at least on draw2d api)

### ISSUE THREAD

**Issue by Nazariglez** [Nazariglez/notan#151]

**Comment by danny-burrows** [comment]
Hi there, apologies if this comment is a little long and I may be misunderstanding details;

I've been attempting to look into this issue and thought it best to share my findings just in-case it proves of use to someone.

I managed to create a somewhat minimal example of what I believe the issue to be.
<details>
  <summary>Minimal Example (based on <code>/examples/draw_image.rs</code>)</summary>

```rust
use notan::draw::*;
use notan::prelude::*;

#[derive(AppState)]
struct State {
    texture: Texture,
    render_texture: RenderTexture,    
}

#[notan_main]
fn main() -> Result<(), String> {
    notan::init_with(init)
        .add_config(DrawConfig)
        .draw(draw)
        .build()
}

fn init(gfx: &mut Graphics) -> State {
    let texture = gfx
        .create_texture()
        .from_image(include_bytes!("assets/ferris.png"))
        .build()
        .unwrap();

    let render_texture = gfx
        .create_render_texture(350, 219)
        .with_filter(TextureFilter::Linear, TextureFilter::Linear)
        .build()
        .unwrap();

    let mut d = render_texture.create_draw();
    d.image(&texture);
    gfx.render_to(&render_texture, &d);

    State { texture, render_texture }
}

fn draw(gfx: &mut Graphics, state: &mut State) {
    let mut draw = gfx.create_draw();
    draw.clear(Color::BLACK);
    draw.image(&state.texture).position(250.0, 200.0);

    println!("{:?}\n\n", &state.texture);
    println!("{:?}\n\n", &state.render_texture.texture());

    draw.image(&state.render_texture).position(250.0, 250.0);
    gfx.render(&draw);
}
```

</details>
It draws ferris twice on top of themself, once as a `Texture` and again as a `RenderTexture`, and as you can see running the example the `RenderTexture` version is inverted.

![image](https://user-images.githubusercontent.com/44483126/195929048-869a03e1-5d13-4fa4-bedb-b7248fde015a.png)

I'm quite new to the codebase but I had a go at digging into the code and got as far as printing out the render commands [via this statement](https://github.com/Nazariglez/notan/blob/develop/crates/notan_glow/src/lib.rs#L455) but alas it seems the two textures are rendered identically as far as I can tell.

<details>
  <summary>Render Command Output</summary>

```sh
Render cmd: Begin { color: Some(Color { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }), depth: None, stencil: None }
Render cmd: Pipeline { id: 3, options: PipelineOptions { color_blend: Some(BlendMode { src: SourceAlpha, dst: InverseSourceAlpha, op: Add }), alpha_blend: None, cull_mode: None, depth_stencil: DepthStencil { write: true, compare: None }, color_mask: ColorMask { r: true, g: true, b: true, a: true }, stencil: None } }
Render cmd: BindTexture { id: 2, slot: 0, location: 0 }
Render cmd: BindBuffer { id: 7 }
Render cmd: BindBuffer { id: 8 }
Render cmd: BindBuffer { id: 9 }
Render cmd: Draw { primitive: Triangles, offset: 0, count: 6 }
Render cmd: Pipeline { id: 3, options: PipelineOptions { color_blend: Some(BlendMode { src: SourceAlpha, dst: InverseSourceAlpha, op: Add }), alpha_blend: None, cull_mode: None, depth_stencil: DepthStencil { write: true, compare: None }, color_mask: ColorMask { r: true, g: true, b: true, a: true }, stencil: None } }
Render cmd: BindTexture { id: 3, slot: 0, location: 0 }
Render cmd: BindBuffer { id: 7 }
Render cmd: BindBuffer { id: 8 }
Render cmd: BindBuffer { id: 9 }
Render cmd: Draw { primitive: Triangles, offset: 6, count: 6 }
Render cmd: End
```
</details>

My best guess is that the issue lies in `impl DeviceBackend for GlowBackend` under `fn render(&mut self, commands: &[Commands], target: Option<u64>)`, the only noticeable difference between rendering `RenderTexture` and `Texture` is that the former passes a `u64` target. However as you can see in the output above I wasn't able to notice anything substantial.

I do hope some of this helps. I'd love to help more but my knowledge of computer graphics prevents me from going much further.

All the best.

**Comment by Nazariglez** [comment]
Hey @danny-burrows! This issue is because OpenGL renders Framebuffers upside down, and the texture attached to the RenderTarget is linked to a Framebuffer internally. 

I am not an expert either, but I think we can manage this from the shaders just inverting the axis y there, only for the Draw2d API:
 
```
if rt {
  invert axis y
} else {
  do nothing
}
```

Users using the `Graphics` API directly should invert themselves the axis like we do [here](https://github.com/Nazariglez/notan/blob/develop/examples/renderer_render_texture.rs#L15). 

I hope to migrate eventually to WebGPU and leave behind these inconsistencies.

I should have explained better on the ticket what the issue was about, so sorry, it's my bad you loose time on this. 
Thank you so much for taking the time to investigate it! I really appreciate it.

**Comment by danny-burrows** [comment]
@Nazariglez Ah I see that makes a lot of sense, thanks so much for the reply and the great explanation! 

I've enjoyed looking into the inner working of Notan, still learning lots but this was a great help. :)

**Comment by Nazariglez** [comment]
I have been checking different ways to achieve this. I am trying to think about how to keep this compatible with a future port to WebGPU and I have to say, it's hard... 

### Invert Y on shaders:
Pretty straightforward, `spirv_cross` allow us to invert the axis y adding `gl_Position.y *= -1.0` at compilation time, making the coordinate system `y-down` as Vulkan does. The main downside is that WebGPU is `y-up` for `NDC` and `y-down` for textures... (same as Dx12 and Metal). So if we do this change, we need to change it back if we move to WebGPU eventually. Or find a way to change the coordinate system on WebGPU which I am not sure if is possible because I know nothing about it. 

### Load images inverted. 
The crate `image` has an option to load images and flip them on the axis y. This works just fine and keeps the coordinate system without changes. We can do this, but it only affects images, `RenderTexture` will keep the drawing upside down. 

### Invert the projection only for Draw2D API
This is the solution I went for. If we detect that the user is drawing to a `RenderTexture` we just multiply the projection to flip the axis y. The main downside is that this only affects the `Draw2d` API. So, users using the `Graphics` API directly should do this manually in their projection or invert the y position on their shaders.

--  

I choose the third option because I don't want to create a breaking change changing the coordinate system for version 0.8 and then, ina. few months (??) migrate to WebGPU and change again how the coordinate system works. I think that the solution with less friction for the users right now is the third one. 

I am open to ideas though. 

PD: [WebGPU coordinate system](https://github.com/gpuweb/gpuweb/issues/416)
