### ISSUE TITLE
Get size of rendered text 

### ISSUE THREAD

**Issue by LedinecMing** [Nazariglez/notan#164]
Need a method to get size of text that will be rendered

**Comment by UE2020** [comment]
HTML5's CanvasRenderingContext2D has a function called `measureText` for this.

**Comment by LedinecMing** [comment]
> HTML5's CanvasRenderingContext2D has a function called `measureText` for this.

What about non-wasm?

**Comment by Nazariglez** [comment]
Hello! Notan doesn't use the CanvasRenderingContext or it doesn't "move" either the text drawn on the context 2d to the WebGL renderer as most Html engines do, but it uses instead  [glyph_brush](https://github.com/alexheretic/glyph-brush) to create the glyph for any platform. 

We [had once](https://github.com/Nazariglez/notan/blob/200bfda5a58c4394b911a2257668685cf9749f5f/notan/crates/notan_glyph/src/font.rs#L17) a way to measure the text size, but it seems that it was removed due to a big refactor (my fault). The library has changed since then (both glyph and notan), so I need to test and find a proper way to do this, keeping the API simple. It should be an easy change, I hope to pull it this week. 

Sorry for the inconvenience.

**Comment by LedinecMing** [comment]
P.s: this function is really important for my code to work properly
