### ISSUE TITLE
Setting fragment shader for shapes

### ISSUE THREAD

**Issue by michaelni678** [Nazariglez/notan#171]
[suggestion]
There should be an option to pass frag shaders along with the DrawConfig so that you can use certain shaders for certain shapes, images, etc
Alternatively, there can be like a fragment shader map, and you can either do
draw.rectangle().position().etc().frag_shader(water) // sets fragment shader of rectangle to a water shader
or
draw.set_frag_shader(water)
draw.rectangle().position().etc() // draws with water fragment shader
draw.triangle().position().etc() // draws with water fragment shader

**Comment by Nazariglez** [comment]
I found a bug in the custom pipeline system for the Draw2d API, the feature of using a custom shader on shapes was broken. It should be fixed with this (once merged): https://github.com/Nazariglez/notan/pull/176/files#diff-2fc93cd8e32aaf04b5b34c3d119485b0bd11ab286bfc2ebbdce46e809fa9194fR72-R92 

I am still thinking about the ability to add different shaders and store them and refer to them by name or whatever, it sounds great, but at the same time, it could be "too much" for the API, because is something that can be implemented by the user on top of their code easily. If we do it, we need to add HashMaps and check them at every call, etc...

So I have mixed feelings about it, one side of me thinks that the feature is cool, and the other one thinks that it adds complexity that we may not need because it's easy to add by the user if they need it.

What do you think?

**Comment by michaelni678** [comment]
I guess since notan isn't supposed to be an engine it wouldn't make too much sense to have that. I personally think it would be 
 convenient to have but since I suggested the idea I'm obviously biased. Would be nice to just optionally have it on the side and include it w/ cargotoml {... features = ["shadermap"] ... } or something

**Comment by Nazariglez** [comment]
I am leaning towards not adding the feature because:
* Adding it makes the API more complex
* We have a lot of feature flags right now, and I feel we should reserve them for bigger things, like new graphics APIs, new hardware, or platform features requiring new dependencies. 
* It makes it hard to set uniforms values
* It's easy to add it on top of the Draw2D API for the user. 

I kind of prefer to keep the explicit API that we have `.shape_pipeline()`, `(shape|pattern|image|text)_pipeline()`  to set the shaders, and avoid adding too much opinionate code on top of the lib.

I am closing the issue, but let's keep talking if you want. This is not written in stone, we can always come back to it if we feel that we need it. 

Thanks!
