### ISSUE TITLE
How to use Draw API within egui PaintCallback?

### ISSUE THREAD

**Issue by boxofrox** [Nazariglez/notan#234]
I started a program using the Draw API, and have pivoted to adding a GUI to present internal data.  The problem I have is the DrawAPI draws to the entire window, and the GUI overlaps and covers portions of the former step.

I'd like to take my Draw code, and embed it inside a egui Panel to leverage the egui layout to avoid the overlap.  However, the egui PaintCallback receives a `Device` argument instead of a `Graphics` argument, and `Device` doesn't expose a `create_draw` API like `Graphics` does.

All does not appear to be lost.  `Device::create_render_texture` will provide a `RenderTexture` which has a `create_draw` function.

Here is where I'm stuck.  With `Graphics`, I had to use `gfx.render(&draw)` to show the result of my draw operations on the screen.  I see no API with `RenderTexture` to render the result of my draw operations onto the texture, so I'm not sure if this happens automatically or if I've missed the appropriate API.

Once I draw to the `RenderTexture`, is there a way to render that to the egui region without resorting to the `renderer` API?  I see the *egui_paint` example renders a `RenderTexture` to a quad, but it appears that method requires quite a bit of setup just to use, and I'm curious whether there's a simpler alternative available.

**Comment by riverfr0zen** [comment]
I think you're looking for the render_to method for Graphics: https://docs.rs/notan/0.9.1/notan/app/struct.Graphics.html#method.render_to

You can see how it is used in this example -- and though it doesn't use egui, the example might give you some ideas about positioning your draw alongside the UI.
https://github.com/Nazariglez/notan/blob/main/examples/texture_to_file.rs

**Comment by boxofrox** [comment]
Thanks for pointing out `Graphics::render_to`, but the problem with that is I have no `Graphics` object when the egui `PaintCallback` is triggered.  When execution reaches the callback \[[1](https://github.com/Nazariglez/notan/blob/develop/examples/egui_paint.rs#L145)\], I have a `Device` argument, but no `Graphics` argument.

\[1]: https://github.com/Nazariglez/notan/blob/main/examples/egui_paint.rs#L145

I don't think I can move the `&mut Graphics` object into the callback closure \[[2](https://github.com/Nazariglez/notan/blob/develop/examples/egui_paint.rs#L45)] as that should result in a shared mutable reference when the outer function returns, if I understand Rust correctly.

\[2]: https://github.com/Nazariglez/notan/blob/main/examples/egui_paint.rs#L45

While `Device::render_to` exists, it requires `Command`s instead of `GfxRenderer`, like `Graphics::render_to`.

If it's possible to take the `Device` I have and convert it to a `Graphics`, I'd be happy with that, but I can see how to accomplish that from the functions listed in the API.

**Comment by riverfr0zen** [comment]
Ah sorry, my bad for not reading carefully. Hmm, I'm not sure about the solution but maybe someone else will have an idea. It would be cool if it was possible.

**Comment by Nazariglez** [comment]
hey @boxofrox, welcome!

I am afraid that currently there is no way to access the DrawAPI from egui. The main issue is that the DrawAPI is an extension, same as egui, and because borrow checking issues you cannot use an extension from another, because the container of them is the same... I should think a way to avoid this for next versions. When the implementation was done I though about using an atomic reference for the extensions, but that adds a lot of overhead (locks) no only for this case, but for any draw call then.

Although drawing to a render texture and render the texture inside egui doesn't look like a bad way to handle this for me, I know is not very straightforward, but the alternatives are:
* Use the `Device` object to create anything you need, so you will need to impl yourself shapes, textures or anything you need to use.
* Do not add the draw plugin, and add the ` draw::DrawManager` to your `AppState`, then you can create manually `Draw::new(width, height)` and pass it to the manager to process it (this may require to make some method public). Not sure how easy it will be, never tried before, but it's doable. 
* Last option, do the same as the `egui_render_texture` example, draw first to a RT and then to egui. I simplified the example using the DrawAPI in case it helps:
```
use notan::draw::*;
use notan::egui::{self, *};
use notan::prelude::*;

#[derive(AppState)]
struct State {
    render_texture: RenderTexture,
    tex_id: egui::TextureId,
}

impl State {
    fn new(gfx: &mut Graphics) -> State {
        let render_texture = gfx
            .create_render_texture(400, 400)
            .with_depth()
            .build()
            .unwrap();

        let tex_id = gfx.egui_register_texture(&render_texture);

        Self {
            tex_id,
            render_texture,
        }
    }
}

#[notan_main]
fn main() -> Result<(), String> {
    notan::init_with(State::new)
        .add_config(WindowConfig::new().vsync(true).high_dpi(true))
        .add_config(EguiConfig)
        .add_config(DrawConfig)
        .draw(draw)
        .build()
}

fn draw(app: &mut App, gfx: &mut Graphics, plugins: &mut Plugins, state: &mut State) {
    // draw your things here
    let mut draw = state.render_texture.create_draw();
    draw.clear(Color::MAROON);
    draw.circle(50.0)
        .position(
            state.render_texture.width() * 0.5,
            state.render_texture.height() * 0.5,
        )
        .color(Color::ORANGE);

    gfx.render_to(&state.render_texture, &draw);

    // create an egui output
    let mut output = plugins.egui(|ctx| {
        egui::Window::new("Notan Render Texture").show(ctx, |ui| {
            // draw the render texture to egui
            let size: egui::Vec2 = state.render_texture.size().into();
            ui.image(state.tex_id, size);
        });
    });

    output.clear_color(Color::BLACK);
    gfx.render(&output);
}

```

As I said, I hope to improve this eventually, not beign able to use the `GfxExtensions` from the egui's Paint callback is disappointing :(

**Comment by boxofrox** [comment]
@Nazariglez thanks!  I just couldn't tell on my own whether I could use Draw in both locations with the same ease.

As I want to leverage egui's layout to compute the size of a render_texture, I don't think I'll achieve that with the last option.

I'll look into option 2 and see if I can get something working with the `DrawManager`.
