### ISSUE TITLE
transparent line 

### ISSUE THREAD

**Issue by duckfromdiscord** [Nazariglez/notan#239]
https://github.com/duckfromdiscord/nullrefino/commit/a19fb262863dae8976cd781ecbe470928be57941#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR250

This line of code is producing a transparent line that should be RGBA `1.0, 1.0 ,1.0, 1.0` but it is turning out transparent.

![image](https://user-images.githubusercontent.com/113956421/220440747-b6fdbcb7-3ed4-493a-996c-eb170908f041.png)

**Comment by Nazariglez** [comment]
hey @duckfromdiscord is this on the browser? I am checking it on linux and it looks good, but it doesn't on the browser, when I test on it I got a similar image. I am not sure what it could be right now, because if native is ok, then it must be something at browser level. 

Just confirms me if the issue is browser only, to be sure. Your code looks fine. I am going to think a little bit about what ti can be the issue for the browser.

**Comment by duckfromdiscord** [comment]
this is on windows. browser works 
![image](https://user-images.githubusercontent.com/113956421/220495905-7c20629f-734e-4e54-ab04-2b6f16d20885.png)
this is weird

**Comment by duckfromdiscord** [comment]
that screenshot is on browser. the first one in the first message is windows
