### ISSUE TITLE
Large image files load to black texture

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#251]
When loading very large texture files, they are incorrectly opened due to limits in the `image` crate.

This issue was originally posted here (including a proposed fix in notan):
https://github.com/woelper/oculante/issues/152

In a nutshell, using `image::load_from_memory` has limits set that prevent loading large image files. You can choose your own limits or use `no_limits()` on `image::io::Reader`.

**Comment by Nazariglez** [comment]
Hello, thanks for the heads up, I'll take a look and come back soon!

**Comment by Nazariglez** [comment]
Well, your investigation at https://github.com/woelper/oculante/issues/152 saved me a lot of time, thanks!

I did some changes ([here](https://github.com/Nazariglez/notan/commit/ddc41f244fa7c5da3be2c01dfb93c94d4940f6d7)) to allow loading any image no matter the size. And the issue we have with large texture is 99% because the texture is bigger than allowed by OpenGL. I added a `warning` to inform this. Although I am not sure how to manage this. There are some options:
* Leave a warning, allowing to load the image even if it's displayed as a black rectangle.
* Return an error when creating the texture. Forcing the dev to manage the error or panic. 

My main worry is that this is not something that we can know at compilation time, with that kind of issue I am always prone to panic fast in debug mode. However this case depends on the user's hardware, a panic can be the worst for the user, and a warning log can be insufficient for the app's dev. 

We can go for now with the warning (for `0.9.5`) and change the behavior for `0.10.0`, but I don't know what will be a good solution, to be honest... 

Any thoughts?

**Comment by Quackdoc** [comment]
I think returning an error should be the appropriate solution.

**Comment by woelper** [comment]
I also think an error would be best. In a game, I'd be forced to care about the texture and make sure it has the correct size. In Oculante's case we could either pass the error up or even decide to resize the texture on the fly and display a message.

**Comment by Nazariglez** [comment]
It makes sense, I am doing the change and `0.9.5` will be out this week. Thanks!

**Comment by woelper** [comment]
Amazing, thank you so much! I will build a release for oculante afterwards, lots of other good things in `0.9.5`, too!

**Comment by woelper** [comment]
I did some more investigation, and at least on my system the texture limit is 16384x16384px. Is there any way in `notan` I can get the maximum supported texture size before loading fails? I am thinking of creating multiple textures or resizing the texture to fit before attempting to display it.

**Comment by woelper** [comment]
Thanks @riverfr0zen  - I should have read the docs more thoroughly. This does exactly what I want and - at least in my case - returns the same value. I'll use that!

**Comment by Nazariglez** [comment]
> Is the info returned by Graphics::limits() reliable for this? https://docs.rs/notan/latest/notan/app/struct.Graphics.html#method.limits

Yep, this is the value returned by the GL driver. Should be reliable.

**Comment by Nazariglez** [comment]
This should be done with the latest version on crates.io and the main branch, let me know otherwise, thanks for the help!
