### ISSUE TITLE
Renderer slowing down from 0.8 to 0.9 version

### ISSUE THREAD

**Issue by atminatana** [Nazariglez/notan#257]
renderer_texture example on version up to 0.8 render with ~10000 fps, from version 0.9 ~3000 fps
Linux 6.1, NVidia driver, OpenGL

**Comment by Nazariglez** [comment]
Hello @atminatana have you tried the bunnymark? Do you see any difference there?

**Comment by atminatana** [comment]
Yes. Prefomance down on 10%. It is permissible. But bunnymark use Draw, not Renderer.

**Comment by Nazariglez** [comment]
Is this still an issue? We're on 0.11, about to release 0.12 with some fixes and in the works we have a new rendering 
 backend that will land eventually. 

https://github.com/Nazariglez/notan/pull/299

I am closing it, but feel free to reopen if this is still an issue that you think should be fixed by 0.12 or 0.13. Thanks
