### ISSUE TITLE
Multisampling setting seems to be ignored

### ISSUE THREAD

**Issue by devmeat** [Nazariglez/notan#269]
Changing multisampling seems to have no effect.
Also, there is no way (that I know of) to enable/disable multisampling before draw calls. Which causes a blurry effect on egui.

Hardware:
OS: Win 10 Pro
Graphics card: GTX 1060
Driver: 528.49

```rust
let window_config = WindowConfig::new()
        .set_multisampling(0);
```

**Comment by Nazariglez** [comment]
Hey there @devmeat,

Just to clarify, is this about the native build instead of the web version?

Currently, there's no runtime option to disable/enable multisampling. However, it shouldn't be too difficult to add. Would you be interested in contributing by sending a PR? Your contribution would be highly appreciated.

**Comment by devmeat** [comment]
Hi @Nazariglez 

My apologies for the late response. It is in the native build. 
Currently a bit swamped atm, but will send some PRs your way some time.
