### ISSUE TITLE
This is really cool! Will *definitely* use this!

### ISSUE THREAD

**Issue by eboatwright** [Nazariglez/notan#74]

**Comment by Nazariglez** [comment]
Thank you!

Just curious, what do you miss on the project to start using it already?

I'm trying to get feedback to see how the project can be improved.

**Comment by eboatwright** [comment]
Haven't used it yet, today I'm going to make a little project :) But I'll post my ideas, and things here :D

**Comment by eboatwright** [comment]
Well, first impressions after doing the "Draw Triangle" example, there are *alot* of dependencies, so the initial build, took a while for me, but also just running `cargo run` *after* the initial build still took about 8 seconds for me, but so far really good!

**Comment by eboatwright** [comment]
I think you should rename the .set_config() to .add_config(). Because, when you want to draw stuff, and have the window configuration, you have to call .set_config() twice. Which is a little confusing, because it sounds like you are overriding the first one.

**Comment by Nazariglez** [comment]
> Well, first impressions after doing the "Draw Triangle" example, there are _alot_ of dependencies, so the initial build, took a while for me, but also just running `cargo run` _after_ the initial build still took about 8 seconds for me, but so far really good!

Yeah, I'm trying to only use what I need as dependencies, not sure if I can remove some of them, I'll check it. Although for the next version (`develop` and `f/egui` branches) I cleaned up a little the dependencies.



> I think you should rename the .set_config() to .add_config(). Because, when you want to draw stuff, and have the window configuration, you have to call .set_config() twice. Which is a little confusing, because it sounds like you are overriding the first one.

This makes sense to me, already changes on the `develop' branch. It will arrive on the `0.2.0` version. 



> I really like having the ability to write shaders, and _directly_ integrate them into the rendering! I also, like how the asset loading works. I got a little animated pixel art character moving around the screen with the arrow keys, and got it working on WASM! The only thing right now is, I can't figure out how to flip the character

The initial idea of the draw2d render was to provide an easy way draw on the screen but allowing the user to use their own matrices to transform the render. I added some helpers like `rotate_from`or `scale_from` to help with the transformation, and I guess that I can add another function to help with the mirroring, it makes sense because it's something common. 

A workaround for now could be `scale_from(your_center_point, (-1, 1))`. That should flip the object horizontally from the center. But as I said I'll think about add a flip function.

Thanks you so much for your feedback! If you find anything else let me know!

**Comment by eboatwright** [comment]
Ok that's good! Your welcome :) I'll try adding that to my little test project :smile:

**Comment by Nazariglez** [comment]
Closing this, feel free to reopen o create a new issue if you think that we should change or add something. Thanks!

**Comment by eboatwright** [comment]
Alrighty!
