### ISSUE TITLE
Expose winit's decorations and transparency options to WindowConfig

### ISSUE THREAD

**Issue by broomlytinum** [Nazariglez/notan#97]
I'm unsure if this was an intentional decision or not, but it would be nice to have these window options, especially considering winit already provides them. I made a fork with these changes but quite frankly I'm new to contributing so I don't know if I should go ahead and submit a pull request. Regardless, I figured there may be a reason as to why these options weren't exposed, so I thought I'd ask here first.

(A side note: I'm very impressed by Notan! I much appreciate the straightforward and easy-to-use API. The extensive number of demos is wonderful, and I'm happy to see that it isn't very memory-intensive (at least for toy examples). Thank you for your hard work!)

**Comment by Nazariglez** [comment]
Thanks for the kind words!

I will gladly accept a PR with transparency and decoration. It wasn't there because I'm trying to keep as many features as I can cross-compatible, and I guess that those don't fit the web environment well. 

We have two options here: expose the windows backend (winit) or add these options to the WindowConfig struct and only use on winit. Which one do you think it's better? I don't have a strong opinion, I need to think about it a little.
